## Documentation: http://docs.travis-ci.com/user/languages/julia/

language: julia

julia:
  - 0.7
  - 1.0
  - nightly

os:
  - linux
  - osx

matrix:
 allow_failures:
 - julia: nightly

notifications:
  email: false

before_script:
  - export PATH=$HOME/.local/bin:$PATH

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.clone("uCSV"); Pkg.build("uCSV"); Pkg.test("uCSV"; coverage=true)'

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("uCSV")); Pkg.add("Documenter"); Pkg.add("DataFrames"); Pkg.add("CodecZlib"); Pkg.add("Missings"); Pkg.add("CategoricalArrays"); include(joinpath("docs", "make.jl"))'
  - julia -e 'using Pkg; cd(Pkg.dir("uCSV")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
